const bolygok=[
    {   id:1,
        name:'Merkúr',
        img:'merkur.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010301Merkur/merkur.html' },
    {   id:2,
        name:'Vénusz',
        img:'venusz.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010302Venusz/venusz.html' },
    {   id:3,
        name:'Föld',
        img:'fold.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/01030301Fold/fold.html' },
    {   id:4,
        name:'Mars',
        img:'mars.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010304Mars/Mars.html' },
    {   id:5,
        name:'Jupiter',
        img:'jupiter.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010305Jupiter/Jupiter.html' },
    {   id:6,
        name:'Szaturnusz',
        img:'saturn.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010306Szaturnusz/Szaturnusz.html' },
    {   id:7,
        name:'Uránusz',
        img:'uranus.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010308Neptunusz/Neptunusz.html' },
    {   id:8,
        name:'Neptunusz',
        img:'neptun.jpg',
        descr:'http://astro.u-szeged.hu/oktatas/csillagaszat/6_Naprendszer/010308Neptunusz/Neptunusz.html' },
]